// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NSA.Persistence;

#nullable disable

namespace NSA.Persistence.Migrations
{
    [DbContext(typeof(NotificationDbContext))]
    [Migration("20260709080957_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NSA.Domain.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("VisitorEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("VisitorEmail", "ProductId")
                        .IsUnique();

                    b.ToTable("CartItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 9, 2, 10, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ProductId = 1,
                            Quantity = 2,
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 9, 2, 10, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VisitorEmail = "bmacha2015@gmail.com"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 9, 2, 12, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ProductId = 4,
                            Quantity = 1,
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 9, 2, 12, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VisitorEmail = "bmacha2015@gmail.com"
                        });
                });

            modelBuilder.Entity("NSA.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTimeOffset?>("SentAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "Order #1 for bmacha2015@gmail.com. Status: Delivered; Payment: Paid; Fulfillment: AssignedToRider; Delivery: Delivered. Total: PHP 1277.00.",
                            Channel = "Email",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 8, 3, 31, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsRead = true,
                            OrderId = 1,
                            RecipientEmail = "bmacha2026@gmail.com",
                            SentAtUtc = new DateTimeOffset(new DateTime(2026, 7, 8, 3, 31, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Subject = "New order #1"
                        },
                        new
                        {
                            Id = 2,
                            Body = "Your order #1 was received and is now delivered. Total: PHP 1277.00.",
                            Channel = "Email",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 8, 3, 32, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsRead = true,
                            OrderId = 1,
                            RecipientEmail = "bmacha2015@gmail.com",
                            SentAtUtc = new DateTimeOffset(new DateTime(2026, 7, 8, 3, 32, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Subject = "Order #1 received"
                        },
                        new
                        {
                            Id = 3,
                            Body = "Order #1 is delivered. Thank you for your purchase.",
                            Channel = "Email",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 8, 5, 15, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsRead = false,
                            OrderId = 1,
                            RecipientEmail = "bmacha2015@gmail.com",
                            SentAtUtc = new DateTimeOffset(new DateTime(2026, 7, 8, 5, 15, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Subject = "Order #1 status updated"
                        },
                        new
                        {
                            Id = 4,
                            Body = "Order #2 for bmacha2015@gmail.com. Status: Preparing; Payment: Paid; Fulfillment: Packing; Delivery: WaitingForRider. Total: PHP 1398.00.",
                            Channel = "Email",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 9, 1, 46, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsRead = false,
                            OrderId = 2,
                            RecipientEmail = "bmacha2026@gmail.com",
                            SentAtUtc = new DateTimeOffset(new DateTime(2026, 7, 9, 1, 46, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Subject = "New order #2"
                        },
                        new
                        {
                            Id = 5,
                            Body = "Your order #2 was received and is being prepared. Total: PHP 1398.00.",
                            Channel = "Email",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 9, 1, 47, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsRead = false,
                            OrderId = 2,
                            RecipientEmail = "bmacha2015@gmail.com",
                            SentAtUtc = new DateTimeOffset(new DateTime(2026, 7, 9, 1, 47, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Subject = "Order #2 received"
                        });
                });

            modelBuilder.Entity("NSA.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("FulfillmentStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("VisitorEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 8, 3, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DeliveryStatus = "Delivered",
                            FulfillmentStatus = "AssignedToRider",
                            OrderStatus = "Delivered",
                            PaymentStatus = "Paid",
                            TotalAmount = 1277.00m,
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 8, 5, 15, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VisitorEmail = "bmacha2015@gmail.com"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 9, 1, 45, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DeliveryStatus = "WaitingForRider",
                            FulfillmentStatus = "Packing",
                            OrderStatus = "Preparing",
                            PaymentStatus = "Paid",
                            TotalAmount = 1398.00m,
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 9, 2, 5, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VisitorEmail = "bmacha2015@gmail.com"
                        });
                });

            modelBuilder.Entity("NSA.Domain.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            ProductId = 2,
                            ProductName = "Butter Croissant Box",
                            Quantity = 1,
                            Subtotal = 429.00m,
                            UnitPrice = 429.00m
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 1,
                            ProductId = 3,
                            ProductName = "Gourmet Sandwich Kit",
                            Quantity = 1,
                            Subtotal = 549.00m,
                            UnitPrice = 549.00m
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 1,
                            ProductId = 4,
                            ProductName = "Fresh Berry Bowl",
                            Quantity = 1,
                            Subtotal = 299.00m,
                            UnitPrice = 299.00m
                        },
                        new
                        {
                            Id = 4,
                            OrderId = 2,
                            ProductId = 5,
                            ProductName = "Signature Pasta Tray",
                            Quantity = 2,
                            Subtotal = 1398.00m,
                            UnitPrice = 699.00m
                        });
                });

            modelBuilder.Entity("NSA.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantityAvailable")
                        .HasColumnType("int");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(280)
                        .HasColumnType("nvarchar(280)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A balanced medium roast with cocoa notes for daily brewing.",
                            ImageUrl = "https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=900&q=80",
                            Name = "Artisan Coffee Beans",
                            Price = 349.00m,
                            QuantityAvailable = 100,
                            ShortDescription = "Small-batch roasted arabica beans."
                        },
                        new
                        {
                            Id = 2,
                            Description = "A six-piece box of layered butter croissants for breakfast or gifting.",
                            ImageUrl = "https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=900&q=80",
                            Name = "Butter Croissant Box",
                            Price = 429.00m,
                            QuantityAvailable = 50,
                            ShortDescription = "Flaky croissants baked fresh."
                        },
                        new
                        {
                            Id = 3,
                            Description = "Includes artisan bread, deli cuts, crisp greens, and house dressing.",
                            ImageUrl = "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=900&q=80",
                            Name = "Gourmet Sandwich Kit",
                            Price = 549.00m,
                            QuantityAvailable = 35,
                            ShortDescription = "Premium sandwich ingredients ready to assemble."
                        },
                        new
                        {
                            Id = 4,
                            Description = "A chilled fruit bowl with strawberries, blueberries, yogurt, and granola.",
                            ImageUrl = "https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?auto=format&fit=crop&w=900&q=80",
                            Name = "Fresh Berry Bowl",
                            Price = 299.00m,
                            QuantityAvailable = 70,
                            ShortDescription = "Seasonal berries with granola."
                        },
                        new
                        {
                            Id = 5,
                            Description = "Pasta tray prepared for sharing, finished with parmesan and herbs.",
                            ImageUrl = "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=900&q=80",
                            Name = "Signature Pasta Tray",
                            Price = 699.00m,
                            QuantityAvailable = 25,
                            ShortDescription = "Family-size pasta with tomato basil sauce."
                        });
                });

            modelBuilder.Entity("NSA.Domain.Entities.CartItem", b =>
                {
                    b.HasOne("NSA.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("NSA.Domain.Entities.Notification", b =>
                {
                    b.HasOne("NSA.Domain.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Order");
                });

            modelBuilder.Entity("NSA.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("NSA.Domain.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NSA.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("NSA.Domain.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
